Traceback (most recent call last):
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\homework-wandb\scripts\preprocess_data.py", line 96, in <module>
    run_data_prep()
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\homework-wandb\scripts\preprocess_data.py", line 91, in run_data_prep
    artifact.add_dir("." + dest_path)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 440, in add_dir
    raise ValueError("Path is not a directory: %s" % local_path)
ValueError: Path is not a directory: ../output