Traceback (most recent call last):
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\apis\public.py", line 957, in artifact
    entity, project, artifact_name = self._parse_artifact_path(name)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\apis\public.py", line 672, in _parse_artifact_path
    raise ValueError("Invalid artifact path: %s" % path)
ValueError: Invalid artifact path: afk-legacy/NYC_TAXI_MODULE_2/artifacts/NYC-Taxi:v0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\homework-wandb\scripts\train.py", line 63, in <module>
    run_train()
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\homework-wandb\scripts\train.py", line 41, in run_train
    artifact = wandb.use_artifact(data_artifact, type="preprocessed_dataset")
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2676, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\apis\normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\apis\public.py", line 957, in artifact
    entity, project, artifact_name = self._parse_artifact_path(name)
  File "d:\Dev\projects\MLOpsZoomcamp\Module2\.venv\lib\site-packages\wandb\apis\public.py", line 672, in _parse_artifact_path
    raise ValueError("Invalid artifact path: %s" % path)
wandb.errors.CommError: Invalid artifact path: afk-legacy/NYC_TAXI_MODULE_2/artifacts/NYC-Taxi:v0